### ISSUE TITLE
Content Descriptor initialisation crashes with a null pointer

### ISSUE THREAD

**Issue by humblerookie** [aosp-mirror/platform_frameworks_base#118]
A lot of my users are facing a NullPointerException issue while instantiating content descriptor.

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.UriMatcher.mText' on a null object reference
       at android.content.UriMatcher.addURI(UriMatcher.java:186)
       at com.getsuperapp.chat.db.ContentDescriptor.getUriMatcher(SourceFile:25)
       at com.getsuperapp.chat.db.DatabaseProvider.query(SourceFile:33)
       at android.content.ContentProvider.query(ContentProvider.java:1017)
       at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
       at android.content.ContentResolver.query(ContentResolver.java:497)
       at android.content.ContentResolver.query(ContentResolver.java:439)
```

[Complete crash log and devices](http://crashes.to/s/3297e6797ca)

The weird part is I'm passing constants to the function.

[Relevant code](http://pastie.org/private/gqczzof1d7vkchfnypo7sw)

Can I have some visibility into this issue as I'm unable to reproduce this at my end. Would the reason by any means be a non synchronized access?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
