### ISSUE TITLE
Camera2 API FATAL EXCEPTION : LegacyCameraCallback

### ISSUE THREAD

**Issue by prudhvirajkumar10** [aosp-mirror/platform_frameworks_base#146]
I'm developing a camera app. I have taken the reference from Google's Camera2Video and developed. Whenever I start camera recording the app crashes and showing the log cat as:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest android.hardware.camera2.impl.CameraDeviceImpl$CaptureCallbackHolder.getRequest(int)' on a null object reference
                                                                      at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(CameraDeviceImpl.java:1792)
                                                                      at android.hardware.camera2.legacy.CameraDeviceUserShim$CameraCallbackThread$CallbackHandler.handleMessage(CameraDeviceUserShim.java:316)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by michaelbarlow7** [comment]
I've run into the same problem as well, though it only happens occasionally.

Looking at the code for CameraDeviceImpl, it looks like a provided null-check is not happening as early as it should. See https://github.com/aosp-mirror/platform_frameworks_base/blob/d18ed49f9dba09b85782c83999a9103dec015bf2/core/java/android/hardware/camera2/impl/CameraDeviceImpl.java#L1882

The CaptureCallbackHolder variable `holder` is retrieved from the map, then the `getRequest()` method is called on it. This is where the NPE occurs.

Later, at [line 1891](https://github.com/aosp-mirror/platform_frameworks_base/blob/d18ed49f9dba09b85782c83999a9103dec015bf2/core/java/android/hardware/camera2/impl/CameraDeviceImpl.java#L1891), there is a null check on the `holder` variable, but this comes too late.

Until this is fixed, I'm not sure how to mitigate this in my code to avoid the crash and/or handle it gracefully.

**Comment by endink** [comment]
+1 same bug

**Comment by BonVit** [comment]
Same

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
